### ISSUE TITLE
[SMBX] Issues with moving platforms.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#123]
1. When platform changes direction from upwards to downwards, character will jitter and fail to respond  to jump button press at that moment.
![scr_2016_5_27_22_20_19_703](https://cloud.githubusercontent.com/assets/7596025/15619751/e743638e-245e-11e6-94a8-ec1011f670da.png)
2. Moving platform can, all of the sudden, drop off middle of the diagonal path.
![scr_2016_5_27_22_20_38_710](https://cloud.githubusercontent.com/assets/7596025/15619799/30043c4c-245f-11e6-88df-f8120e76ed52.png)
Test level: https://yadi.sk/d/qEbMZJa2s4ra6

**Comment by Wohlstand** [comment]
1) That is imperfections at Speed-adding stack system where I still lack some things to correctly change speed of standing on top objects immediately
2) That already fixed in laboratory, but alone imperfection is a 90 degrees crossing paths where platform stucks, but it must follow by it's direction
Video demo of current laboratory build (with updated scripts where is fixed platform.lua!)
https://yadi.sk/i/W9Cbe7g0s4wYz

**Comment by Alucard648** [comment]
Item 1 from this issue is still reproducible with new physics engine.
