### ISSUE TITLE
2 issues with event trigger slots

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#68]
1. OnActivation event trigger slot does not work at all.
2. OnDeath event slot does not trigger, if NPC falls off bottom of the screen.

Test level: https://yadi.sk/d/ymB34-ldj2Z34

**Comment by Wohlstand** [comment]
All right, that was a bug of PGE Editor before I applied fix to it (in the GitHub sources now). Bug causes missing of of "onActivation" event trigger field if you have no "attach layer" field contents. If I will send to you same level but fixed by me and re-saved with fixed version of PGE Editor, you will get everything fine (run level in engine directly or via "test saved file" without re-saving of it). This bug is not applies to SMBX LVL file saved by same version of the editor.
Test level saved by editor built from current state of source code: https://yadi.sk/d/yHI3Op5Xj2azk

**Comment by Wohlstand** [comment]
P.S> Take the current Windows build: https://yadi.sk/d/AwElMratj2d7C
And don't forget the update for SMBX config pack: https://yadi.sk/d/tVNHwG9Xj2dMk (unpack into configs/SMBX!)
Note: You may have bugs with slopes (I wasn't finished yet it!), and slopes are works with playable only, not with NPC's.
Unpack this archive with overwriting of your current state

**Comment by Alucard648** [comment]
NPC falling off bottom of the screen still does not trigger his OnDeath event slot.

**Comment by Wohlstand** [comment]
...because I wasn't implemented death on fall out for NPCs. (which required by both Bowser and other bosses), and those NPC's are goind to be deactivated (but, Bowser has no deactivation way, therefore it will fall down into infinite pit)

**Comment by Wohlstand** [comment]
Okay, I was been implemented ability to kill some NPC's on pit fall: there are Bowser and some bosses which are will die on fall into the fill (with triggering of required events)

**Comment by Alucard648** [comment]
I am suggesting to have all other gravity-affected enemy NPC`s to die by falling down pits. I have seen levels where player needs to trick NPC, like thwomp or goomba-like invincible one to fall off the screen to trigger onDeath events.
